Update deploy_nginx.yaml

diff --git a/.github/workflows/deploy_nginx.yaml b/.github/workflows/deploy_nginx.yaml
--- a/.github/workflows/deploy_nginx.yaml
+++ b/.github/workflows/deploy_nginx.yaml
@@ -37,12 +37,20 @@ jobs:
         run: ls -R; pwd
 
       - name: Build Docker image
-        run: docker build --network=host -t "${{ env.REGISTRY }}/${{ github.actor }}/secure-nginx:1.19-alpine${{ github.sha }}" QA-01/. || exit 1
+        run: docker build --network=host -t "${{ env.REGISTRY }}/${{ github.actor }}/secure-nginx:1.19-alpine${{ github.sha }}" QA-0#1/. || exit 1
 
+#      - name: Run container and check tini
+#        run: |
+#          docker run --rm "${{ env.REGISTRY }}/${{ github.actor }}/secure-nginx:1.19-alpine${{ github.sha }}" \
+#            sh -c "[ -x /sbin/tini ] && echo 'Tini is installed and executable' || { echo 'Tini check failed'; exit 1; }" 
+
+            
       - name: Run container and check tini
         run: |
           docker run --rm "${{ env.REGISTRY }}/${{ github.actor }}/secure-nginx:1.19-alpine${{ github.sha }}" \
-            sh -c "[ -x /sbin/tini ] && echo 'Tini is installed and executable' || { echo 'Tini check failed'; exit 1; }"
+            sh -c "if [ -x /sbin/tini ]; then echo 'Tini is installed and executable'; else echo 'Tini check failed'; exit 1; fi && \
+                   echo 'User running Nginx:' && ps -eo user,comm | grep nginx && \
+                   echo 'Ports Nginx is listening on:' && netstat -tuln | grep nginx"
 
 
       - name: Scan with Trivy
